# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

export ADOTDIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/antigen"
export DOTFILES=$HOME/.dotfiles
DOTFILES_SHELL=$DOTFILES/shell
ZSH=$DOTFILES_SHELL/oh-my-zsh
ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_CUSTOM=$DOTFILES_SHELL/zsh
export ZDOTDIR="${ZSH_CUSTOM}"
HOMEBREW_PREFIX=/opt/homebrew
export XDG_DATA_HOME="${HOME}/.local/share"

# MacOS-specific services
if [ "$(uname -s)" = "Darwin" ]; then
  # Add Brew to path, if it's installed
  if [[ -d /opt/homebrew/bin ]]; then
    # export PATH=/opt/homebrew/bin:$PATH
    eval $(/opt/homebrew/bin/brew shellenv)
  fi
fi
# if ! hash brew 2> /dev/null; then
#   eval $(/opt/homebrew/bin/brew shellenv)
# fi

# Source all ZSH config files (if present)
if [[ -d $ZDOTDIR ]]; then
  # Setup Antigen, and import plugins
  source ${ZDOTDIR}/helpers/setup-antigen.zsh
  source ${ZDOTDIR}/helpers/import-plugins.zsh
fi

# Source custom functions
source $DOTFILES_SHELL/zsh/functions/*.zsh

# Plugins list
# plugins=(zsh-completions zsh-autosuggestions zsh-better-npm-completion zsh-syntax-highlighting history-substring-search jsontools sudo urltools web-search git gpg-agent ssh-agent node npm vscode)

# Setup plugin `history-substring-search`
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Source Oh My Zsh
# source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
