" Setup Vim Plugged, and load plugins
source ~/.vim/setup-vim-plug.vim

filetype plugin on

" ================ General Config ====================

"turn on syntax highlighting
syntax on

" Colors
colorscheme smyck

" ================ Turn Off Swap Files ==============

set noswapfile
set nobackup
set nowb
