export ADOTDIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/antigen"
export DOTFILES="${HOME}/.dotfiles"
export ZDOTDIR="${DOTFILES}/config/zsh"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CONFIG_HOME="${HOME}/.config"
# ZSH_THEME="powerlevel10k/powerlevel10k"
# HOMEBREW_PREFIX=/opt/homebrew

# MacOS-specific services
if [ "$(uname -s)" = "Darwin" ]; then
  # Add Brew to path, if it's installed
  if [[ -d /opt/homebrew/bin ]]; then
    eval $(/opt/homebrew/bin/brew shellenv)
  fi
fi

# Source all ZSH config files (if present)
if [[ -d $ZDOTDIR ]]; then
  # Setup Antigen, and import plugins
  source ${ZDOTDIR}/helpers/setup-antigen.zsh
  source ${ZDOTDIR}/helpers/import-plugins.zsh
fi

# Source custom functions
source ${ZDOTDIR}/functions/*.zsh

# Plugins list
# plugins=(zsh-completions zsh-autosuggestions zsh-better-npm-completion zsh-syntax-highlighting history-substring-search jsontools sudo urltools web-search git gpg-agent ssh-agent node npm vscode)

# Setup plugin `history-substring-search`
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Source Oh My Zsh
# source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
